### ISSUE TITLE
Icono industry

### ISSUE THREAD

**Issue by madurna** [madurna/S18-Proyecto#10]
Jony cuando puedas me podes conseguir un icono asi o ver como agregar esto al proyecto

http://fortawesome.github.io/Font-Awesome/icon/industry/

Gracias

**Comment by Jony02** [comment]
ok, para que parte es el icono?, asi pruebo donde incluirlo.

2016-02-05 0:39 GMT-03:00 madurna notifications@github.com:

**Comment by madurna** [comment]
@Jony02 Hoy subo una nueva version de la base, porque yo estuve haciendo cambios, asi actualizas y queda andando.
Capturo algunas imagenes y te explico donde tendria que ir

**Comment by madurna** [comment]
@Jony02  Tiene que ir en lugar de "Ver", hay que agregarlo en algún lugar del CSS.
El código esta en inc/comun.php, linea 1078, la función se llama "get_plantas_cliente".

![sin titulo](https://cloud.githubusercontent.com/assets/12115196/12868552/ad607f54-cce7-11e5-8d4a-0b6c9da1a47e.jpg)
