### ISSUE TITLE
Planos PDF

### ISSUE THREAD

**Issue by francassi8** [madurna/S18-Proyecto#14]
En los campos que dice "planos" (por ejemplo en la carga de trommel, cinta o prensa) la idea es que abra una ventana de carga de archivos, para poder previsualizar una imagen o pdf

![1-cargar plano](https://cloud.githubusercontent.com/assets/15112394/16636524/fe9eae5c-43ae-11e6-89f7-755ecf7e4867.JPG)

**Comment by madurna** [comment]
Esta bien esto pero esta relacionado con #13
