### ISSUE TITLE
No se tienen permisos de Acceso para algunas páginas

### ISSUE THREAD

**Issue by Jony02** [madurna/S18-Proyecto#27]
Para los archivos agregados que no los deja acceder el navegador, es porque faltan los modulos de los permisos en la BD. Hay que agregarlos
![image](https://cloud.githubusercontent.com/assets/11827860/16891587/92e061f8-4ad2-11e6-9252-0592bca87115.png)

Y que queden así

![image](https://cloud.githubusercontent.com/assets/11827860/16891594/b1fbab9c-4ad2-11e6-874f-aa60c457c022.png)

Después hacen el Logout e ingresan de nuevo para que haga la asignacion de los permisos.

No actualizo la BD porque estuve cambiando algunos valores a manos para hacer pruebas y no sé si quedó del todo bién

**Comment by madurna** [comment]
No entiendo porque este ticket

**Comment by Jony02** [comment]
Te entendí por Whatsapp que lo suba acá para no olvidarnos de nada cuando se lo mostremos a Rubén. Si no era eso lo cierro nomás

**Comment by madurna** [comment]
Lo que yo digo es de crear un issues que se llame "Paginas nuevas" y vamos agregando las nuevas cada uno, que este solo el directorio, por ejemplo, planta/planta.php, asi cuando vayamos a mostrarle a Ruben nos fijamos en el issues que esten esas paginas nuevas dadas de alta en los modulos.

**Comment by Jony02** [comment]
ahora entendí, cierro este así no molesta entonces
